/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/examples/HelloWorld.vue')['default']
    IconArrowHook: typeof import('./src/components/icons/IconArrowHook.vue')['default']
    IconCart: typeof import('./src/components/icons/IconCart.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconCurrency: typeof import('./src/components/icons/currency/IconCurrency.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconDollar: typeof import('./src/components/icons/currency/IconDollar.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconEuro: typeof import('./src/components/icons/currency/IconEuro.vue')['default']
    IconGooglePay: typeof import('./src/components/icons/IconGooglePay.vue')['default']
    IconShoppingCart: typeof import('./src/components/icons/IconShoppingCart.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDivider: typeof import('naive-ui')['NDivider']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NPopselect: typeof import('naive-ui')['NPopselect']
    PageFooter: typeof import('./src/components/layout/footer/page-footer.vue')['default']
    PageHeader: typeof import('./src/components/layout/header/page-header.vue')['default']
    PageHeaderRight: typeof import('./src/components/layout/header/page-header-right.vue')['default']
    ProductCard: typeof import('./src/components/products/ProductCard.vue')['default']
    ProductDetailDescription: typeof import('./src/components/products/product-detail/product-detail-description.vue')['default']
    ProductDetailHeader: typeof import('./src/components/products/product-detail/product-detail-header.vue')['default']
    ProductDetailRecommendations: typeof import('./src/components/products/product-detail/product-detail-recommendations.vue')['default']
    ProductPayment: typeof import('./src/components/products/product-checkout/product-payment.vue')['default']
    ProductSummary: typeof import('./src/components/products/product-checkout/product-summary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/examples/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/examples/WelcomeItem.vue')['default']
  }
}
